"""phase2 raw payload and run stats

Revision ID: aede502fc485
Revises: 6a24f4bbfb48
Create Date: 2026-07-27 15:27:54.378779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aede502fc485'
down_revision: Union[str, None] = '6a24f4bbfb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('raw_payload', sa.JSON(), nullable=True))
    op.add_column('runs', sa.Column('stats_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'stats_json')
    op.drop_column('reviews', 'raw_payload')
    # ### end Alembic commands ###
